-- 코드를 입력하세요
SELECT
    U.USER_ID AS USER_ID,
    U.NICKNAME AS NICKNAME,
    CONCAT(U.CITY,' ',U.STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소',
    CONCAT(
        SUBSTRING(U.TLNO,1,3),'-', -- 1번째부터 3글자
        SUBSTRING(U.TLNO,4,4),'-', -- 4번째부터 4글자
        SUBSTRING(U.TLNO,8,4) -- 8번째부터 4글자
    ) AS '전화번호'
    
FROM
    USED_GOODS_BOARD B
JOIN
    USED_GOODS_USER U ON U.USER_ID=B.WRITER_ID
WHERE
    U.USER_ID IN (
    SELECT WRITER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(*)>=3)
GROUP BY
    U.USER_ID
ORDER BY
    U.USER_ID DESC
    