-- 테이블을 ID 기준으로 연결
-- SALES_DATE 1월인거 거름
-- ID ,CATEGORY 그룹핑
-- SUM(SALES) 구함

SELECT
    B.CATEGORY AS CATEGORY,
    SUM(S.SALES) AS TOTAL_SALES
FROM
    BOOK B
INNER JOIN
    BOOK_SALES S ON S.BOOK_ID=B.BOOK_ID
WHERE
    MONTH(S.SALES_DATE)=1
GROUP BY
    B.CATEGORY
ORDER BY
    B.CATEGORY ASC